# handler2.yaml
---
- name: Handler Example2
  hosts: serverb
  gather_facts: true
  become: true
  tasks:
    - name: print message-1
      debug:
        msg: "First Message"
      changed_when: true  #?
      notify: run_handler
    
    - name: pring message-2
      debug:
        msg: "Second Message"
      changed_when: false
      notify: run_handler

  handlers:
    - name: run_handler
      debug:
        msg: "Today's date and time: {{ '%d-%m-%Y %H:%M:%S' | strftime }}"
