# handler.yaml
---
- name: Handler Example
  hosts: serverb
  gather_facts: false
  tasks:
    - name: Installl httpd latest version
      yum:
        name: httpd
        state: latest
      become: true
      notify: restarted_httpd

  handlers:
    - name: restart_httpd
      become: true
      service: 
        name: httpd
        state: started
