# vhost-ansible/tasks/main.yml
---
- name: Install httpd package
  yum:
    name: httpd
    state: latest

- name: Create directory
  file:
    path: /var/www/vhosts/{{ ansible_hostname }}
    state: directory

- name: Started and enabled httpd service
  service:
    name: httpd
    state: started
    enabled: true

- name: Install vhost file
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart httpd
